# Server properties
server:
  port: 8111

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Profile Service - Local Instance

# Spring application properties
spring:
  application:
    name: users-profile
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:discovery://config-server
      - optional:file:./env.properties
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DB_DRIVER_CLASS:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}

# AWS configuration
aws:
  accessKey: ${AWS_ACCESS_KEY:dummy-key}
  secretKey: ${AWS_SECRET_KEY:dummy-secret}
  s3:
    region: ${AWS_S3_REGION:dummy-region}
    avatarBucketName: ${AWS_AVATAR_BUCKET_NAME:dummy-bucket}

# Eureka configuration
eureka:
  client:
    fetchRegistry: ${EUREKA_DISCOVERY_ENABLED:false}
    registerWithEureka: ${EUREKA_DISCOVERY_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

# RabbitMQ settings
rabbitmq:
  exchange: ${RMQ_EXCHANGE:dummy-exchange}
  queues:
    profile-setup: ${RMQ_PROFILE_SETUP_Q:dummy-queue}
    delete-user-data: ${RMQ_DELETE_USER_DATA_Q:dummy-queue}
  routing-keys:
    profile-setup: ${RMQ_PROFILE_SETUP_RK:dummy-key}
    delete-user-data: ${RMQ_DELETE_USER_DATA_RK:dummy-key}

# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mariuszilinskas.vsp: DEBUG
