# Server properties
server:
  port: 8111

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Profile Service - Local Instance

# Spring application properties
spring:
  application:
    name: users-profile
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL}
      - optional:file:./env.properties
  datasource:
    url: ${DB_URI}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}

# AWS configuration
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  s3:
    region: ${AWS_S3_REGION}
    avatarBucketName: ${AWS_AVATAR_BUCKET_NAME}

# Eureka configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

# RabbitMQ settings
rabbitmq:
  exchange: ${RMQ_EXCHANGE}
  queues:
    profile-setup: ${RMQ_PROFILE_SETUP_Q}
    delete-user-data: ${RMQ_DELETE_USER_DATA_Q}
  routing-keys:
    profile-setup: ${RMQ_PROFILE_SETUP_RK}
    delete-user-data: ${RMQ_DELETE_USER_DATA_RK}

# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG