# Spring application properties for CI
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# AWS configuration for CI
aws:
  accessKey: dummy-key
  secretKey: dummy-secret
  s3:
    region: dummy-region
    avatarBucketName: dummy-bucket

# RabbitMQ settings for CI
rabbitmq:
  exchange: dummy-exchange
  queues:
    profile-setup: dummy-queue
    delete-user-data: dummy-queue
  routing-keys:
    profile-setup: dummy-key
    delete-user-data: dummy-key

# Eureka configuration for CI
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
