name: Codecov

on:
  push:
    branches: [ main ]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Generate coverage
        run: SPRING_PROFILES_ACTIVE=ci ./gradlew test jacocoTestReport --no-daemon

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}